// GENERATED by scripts/capture-snapshots.mjs — do not edit by hand.
//
// Each row is a real headless-browser capture of the page named in `url`, with the
// PNG and DOM hashed at capture time. Re-run the script to refresh.

export interface Snapshot {
  id: string;
  postId: string;
  url: string;
  pngRef: string;
  domRef: string;
  pngHash: string;
  domHash: string;
  capturedAt: string;
  expandedRegions: number;
  bytes: number;
}

export const snapshots: Snapshot[] = [
  {
    "id": "OBS-CR-01",
    "postId": "CR-01",
    "url": "http://localhost:3170/fixtures/post/CR-01",
    "pngRef": "/snapshots/CR-01.png",
    "domRef": "/snapshots/CR-01.html",
    "pngHash": "sha256-7656eb5d0669776e7ab412da6c5f9b24",
    "domHash": "sha256-32219d622d032af2943ef368da2ed6a9",
    "capturedAt": "2026-08-20T00:05:29.319Z",
    "expandedRegions": 1,
    "bytes": 333557
  },
  {
    "id": "OBS-CR-02",
    "postId": "CR-02",
    "url": "http://localhost:3170/fixtures/post/CR-02",
    "pngRef": "/snapshots/CR-02.png",
    "domRef": "/snapshots/CR-02.html",
    "pngHash": "sha256-f48a9fef7f9710f3022d745a792a9863",
    "domHash": "sha256-5c3af3ec395a43c7e12e1db6aaa8ee8c",
    "capturedAt": "2026-08-20T00:05:29.732Z",
    "expandedRegions": 1,
    "bytes": 351585
  },
  {
    "id": "OBS-CR-03",
    "postId": "CR-03",
    "url": "http://localhost:3170/fixtures/post/CR-03",
    "pngRef": "/snapshots/CR-03.png",
    "domRef": "/snapshots/CR-03.html",
    "pngHash": "sha256-ed7caf3f4d177300b7b1a615e19cef63",
    "domHash": "sha256-d67b91873a2e543c98afb86d800c1ac1",
    "capturedAt": "2026-08-20T00:05:30.103Z",
    "expandedRegions": 0,
    "bytes": 331735
  },
  {
    "id": "OBS-CR-04",
    "postId": "CR-04",
    "url": "http://localhost:3170/fixtures/post/CR-04",
    "pngRef": "/snapshots/CR-04.png",
    "domRef": "/snapshots/CR-04.html",
    "pngHash": "sha256-c420a53b63483355963a0a8d229a7611",
    "domHash": "sha256-918d0582aa6bc14cfbaa7cbbcdb27018",
    "capturedAt": "2026-08-20T00:05:30.489Z",
    "expandedRegions": 1,
    "bytes": 336006
  },
  {
    "id": "OBS-CR-05",
    "postId": "CR-05",
    "url": "http://localhost:3170/fixtures/post/CR-05",
    "pngRef": "/snapshots/CR-05.png",
    "domRef": "/snapshots/CR-05.html",
    "pngHash": "sha256-35391ff8799ea4147f3bcc5984f3bc13",
    "domHash": "sha256-39aa5bdc8748e9cc8c1875ca9ff94820",
    "capturedAt": "2026-08-20T00:05:30.871Z",
    "expandedRegions": 0,
    "bytes": 334502
  },
  {
    "id": "OBS-CR-06",
    "postId": "CR-06",
    "url": "http://localhost:3170/fixtures/post/CR-06",
    "pngRef": "/snapshots/CR-06.png",
    "domRef": "/snapshots/CR-06.html",
    "pngHash": "sha256-7c114c842fb3bff9a2ea0bd4d907279f",
    "domHash": "sha256-7ffa373dfc43c72b1893e5dc2875297b",
    "capturedAt": "2026-08-20T00:05:31.252Z",
    "expandedRegions": 0,
    "bytes": 333413
  }
];
