// GENERATED by scripts/capture-snapshots.mjs — do not edit by hand.
//
// Each row is a real headless-browser capture of the page named in `url`, with the
// PNG and DOM hashed at capture time. Re-run the script to refresh.

export interface Snapshot {
  id: string;
  postId: string;
  url: string;
  pngRef: string;
  domRef: string;
  pngHash: string;
  domHash: string;
  capturedAt: string;
  expandedRegions: number;
  bytes: number;
}

export const snapshots: Snapshot[] = [
  {
    "id": "OBS-CR-01",
    "postId": "CR-01",
    "url": "http://localhost:3192/fixtures/post/CR-01",
    "pngRef": "/snapshots/CR-01.png",
    "domRef": "/snapshots/CR-01.html",
    "pngHash": "sha256-c636424b52106f198bb66bf755e4b001",
    "domHash": "sha256-aa743d4759ae58f828acae185dd065ad",
    "capturedAt": "2026-08-20T00:13:45.443Z",
    "expandedRegions": 1,
    "bytes": 20321
  },
  {
    "id": "OBS-CR-02",
    "postId": "CR-02",
    "url": "http://localhost:3192/fixtures/post/CR-02",
    "pngRef": "/snapshots/CR-02.png",
    "domRef": "/snapshots/CR-02.html",
    "pngHash": "sha256-700b7d244c10b5e5f331dad94c9e132e",
    "domHash": "sha256-acc5f136565eba3c4ed09dd9be1bf106",
    "capturedAt": "2026-08-20T00:13:45.625Z",
    "expandedRegions": 1,
    "bytes": 24759
  },
  {
    "id": "OBS-CR-03",
    "postId": "CR-03",
    "url": "http://localhost:3192/fixtures/post/CR-03",
    "pngRef": "/snapshots/CR-03.png",
    "domRef": "/snapshots/CR-03.html",
    "pngHash": "sha256-9a8b995ebbb7e0f22bab544cd50a2592",
    "domHash": "sha256-9cd27fb6b86284164fc9d9e7f28539cb",
    "capturedAt": "2026-08-20T00:13:45.791Z",
    "expandedRegions": 0,
    "bytes": 19507
  },
  {
    "id": "OBS-CR-04",
    "postId": "CR-04",
    "url": "http://localhost:3192/fixtures/post/CR-04",
    "pngRef": "/snapshots/CR-04.png",
    "domRef": "/snapshots/CR-04.html",
    "pngHash": "sha256-cb47e71221b44908348c98c7256a0d76",
    "domHash": "sha256-c2a7efeec91f4436054cc2f4db62cd63",
    "capturedAt": "2026-08-20T00:13:45.956Z",
    "expandedRegions": 1,
    "bytes": 20111
  },
  {
    "id": "OBS-CR-05",
    "postId": "CR-05",
    "url": "http://localhost:3192/fixtures/post/CR-05",
    "pngRef": "/snapshots/CR-05.png",
    "domRef": "/snapshots/CR-05.html",
    "pngHash": "sha256-8bde51b6ac75ff67eb889523b91362d0",
    "domHash": "sha256-db52e8798025815b671e8201c942ee2d",
    "capturedAt": "2026-08-20T00:13:46.124Z",
    "expandedRegions": 0,
    "bytes": 20169
  },
  {
    "id": "OBS-CR-06",
    "postId": "CR-06",
    "url": "http://localhost:3192/fixtures/post/CR-06",
    "pngRef": "/snapshots/CR-06.png",
    "domRef": "/snapshots/CR-06.html",
    "pngHash": "sha256-44e2ec8cebcde658d050c182e02a3c2c",
    "domHash": "sha256-fd16c8e2c4e2d2acadc274096c34479d",
    "capturedAt": "2026-08-20T00:13:46.291Z",
    "expandedRegions": 0,
    "bytes": 20429
  }
];
